---
services:
  foldingathome:
    image: lscr.io/linuxserver/foldingathome:latest
    container_name: foldingathome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ACCOUNT_TOKEN=${ACCOUNT_TOKEN}
      - MACHINE_NAME=${MACHINE_NAME}
    volumes:
      - /path/to/foldingathome/data:/config
    ports:
      - 7396:7396 #optional
    restart: unless-stopped
